inherit:
  - module_configs/encoder.yaml
  - module_configs/sinkhorn.yaml
  - module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5
  sinkhorn_feature_dim: 16

name: node_align_node_loss
