inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_steps: 6
  sinkhorn_feature_dim: 16

name: isonet_K=6
